
# Server configuration
server.port=8082

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/payment_db
spring.datasource.username=root
spring.datasource.password=Zimbapay@2025
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# External API configuration
zb.api.base-url=https://zbnet.zb.co.zw
zb.api.pick-pending-path=/alerts/payments/pick-all-pending
zb.api.all-payments-path=/alerts/payments/all-payments
zb.api.student-details=/api/billpay/student-details

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.payments=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

jwt.secret=Tz13v8y/B?E(H+MbQeThWmZq4t7w9z$C&F)J@NcRfUjXn2r5u8x/A%D*G-KaPdSg

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

# --- SECURE API CREDENTIALS ---
zb.api.credentials.MUFAKOSEHIGH1=FVIMeh1jHGgX7Y9IUuab3rghJIwmFAkSh1
zb.api.credentials.KUWADZANA2HIGH=ea9a958bd8c51c88a8d4ac8fae2e55kdz2

