
# Server configuration
server.port=8080

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# External API configuration
zb.api.base-url=https://zbnet.zb.co.zw
zb.api.pick-pending-path=/alerts/payments/pick-all-pending
zb.api.all-payments-path=/alerts/payments/all-payments
zb.api.student-details=/api/billpay/student-details

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.payments=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

jwt.secret=Tz13v8y/B?E(H+MbQeThWmZq4t7w9z$C&F)J@NcRfUjXn2r5u8x/A%D*G-KaPdSg

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

# --- SECURE API CREDENTIALS ---
zb.api.credentials.PACHEDU-USD1=@P#%%W0R9D2025
zb.api.credentials.PACHEDU-USD2=@P#%%W0R9D202501
zb.api.credentials.PACHEDU-USD3=@P#%%W0R9D202502
zb.api.credentials.PACHEDU-USD4=@P#%%W0R9D202503
zb.api.credentials.PACHEDU-USD5=@P#%%W0R9D202504
zb.api.credentials.PACHEDU-USD6=@P#%%W0R9D202505
zb.api.credentials.PACHEDU-USD7=@P#%%W0R9D202506
zb.api.credentials.PACHEDU-ZWG=@P#%%W0R9D202508
